//
// Created by spaceeye on 03.06.23.
//

#ifndef LIFEENGINEEXTENDED_ALL_FRONTEND_INCLUDES_H
#define LIFEENGINEEXTENDED_ALL_FRONTEND_INCLUDES_H

#include "impl/QtWindow.h"

#endif //LIFEENGINEEXTENDED_ALL_FRONTEND_INCLUDES_H
