//
// Created by spaceeye on 06.08.22.
//

#ifndef LIFEENGINEEXTENDED_SIMULATIONPARAMETERSTYPES_H
#define LIFEENGINEEXTENDED_SIMULATIONPARAMETERSTYPES_H


enum class ValueType {
    NONE,
    INT,
    FLOAT,
};
#endif //LIFEENGINEEXTENDED_SIMULATIONPARAMETERSTYPES_H
